[tox]
requires =
  tox>=4
  tox-uv>=1
env_list = lint, type, py{39,310,311,312,313,314}, styled_text, doctest
skip_missing_interpreters = true

[gh-actions]
python =
    3.9: py39, styled-text
    3.10: py310, styled-text
    3.11: py311, styled-text
    3.12: py312, styled-text
    3.13: py313, styled_text, lint, type
    3.14: py314, styled_text

[testenv]
runner = uv-venv-lock-runner
extras = dev
description = run unit tests
deps =
    pytest>=7
    pytest-sugar
commands =
    pytest {posargs:tests}

[testenv:styled-text]
runner = uv-venv-lock-runner
extras =
    dev
    styled-text
description = run unit tests
deps =
    pytest>=7
    pytest-sugar
commands =
    pytest -m "styled_text"

[testenv:lint]
runner = uv-venv-lock-runner
description = run linter
skip_install = true
deps =
    black>=23.9.1
commands = black {posargs:.}

[testenv:type]
runner = uv-venv-lock-runner
extras = dev
description = run type checks
deps =
    mypy>=0.991
commands =
    mypy {posargs:mdfy}

[testenv:doctest]
runner = uv-venv-lock-runner
extras = dev
description = run doctest checks
deps =
    xdoctest>=1.2.0
commands =
    xdoctest mdfy --quiet --nocolor

[testenv:doctest-styled-text]
runner = uv-venv-lock-runner
extras =
    dev
    styled-text
description = run doctest checks
deps =
    xdoctest>=1.2.0
commands =
    xdoctest mdfy --quiet --nocolor
